name: Deploy Backend

on:
  push:
    branches:
      - "*"

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          submodules: "true"

      - name: Set environment variables
        run: |
          if [ "${{ github.ref_name }}" == "main" ]; then
            echo "ENV_NAME=prod" >> $GITHUB_ENV
            echo "PORT=5001" >> $GITHUB_ENV
            echo "TMUX_SESSION=prod-homelabinator-backend" >> $GITHUB_ENV
          else
            echo "ENV_NAME=dev" >> $GITHUB_ENV
            echo "PORT=5000" >> $GITHUB_ENV
            echo "TMUX_SESSION=dev-homelabinator-backend" >> $GITHUB_ENV
          fi

      - name: Deploy to remote
        env:
          REMOTE_USER: snowflake
          REMOTE_HOST: 0.0.0.0
          REMOTE_BASE_DIR: homelabinator-backend
          FORM_URL: ${{ secrets.FORM_URL }}
        run: |
          REMOTE_TARGET_DIR="${REMOTE_BASE_DIR}/${{ env.ENV_NAME }}"
          
          ssh "${REMOTE_USER}@${REMOTE_HOST}" "rm -rf ${REMOTE_TARGET_DIR}"
          rsync -avz --exclude '.**' --exclude '.*' ./ "${REMOTE_USER}@${REMOTE_HOST}:${REMOTE_TARGET_DIR}/"
          ssh "${REMOTE_USER}@${REMOTE_HOST}" "tmux kill-session -t ${{ env.TMUX_SESSION }} 2>/dev/null || true"
          ssh "${REMOTE_USER}@${REMOTE_HOST}" "mkdir -p ~/${REMOTE_TARGET_DIR}/api/isos/"
          ssh "${REMOTE_USER}@${REMOTE_HOST}" "tmux new-session -d -s ${{ env.TMUX_SESSION }} \"cd ~/${REMOTE_TARGET_DIR}/api && export APP_ENV=${{ env.ENV_NAME }} && export PORT=${{ env.PORT }} && export FORM_URL=${{ env.FORM_URL }} && nix-shell -p python3 uv --command 'uv run --with-requirements requirements.txt app.py'\""
